WIP: check docs in pre-submits
Signed-off-by: Pedro Kaj Kjellerup Nacht <pnacht@google.com>

diff --git a/.github/workflows/pre-submit.actions.yml b/.github/workflows/pre-submit.actions.yml
--- a/.github/workflows/pre-submit.actions.yml
+++ b/.github/workflows/pre-submit.actions.yml
@@ -13,29 +13,38 @@ jobs:
     steps:
       - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
 
-      - name: Set Node.js 16
-        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
-        with:
-          node-version: 16
+      # - name: Set Node.js 16
+      #   uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
+      #   with:
+      #     node-version: 16
 
-      - name: Rebuild the dist/ directory
-        working-directory: actions/installer
-        run: make package
+      # - name: Rebuild the dist/ directory
+      #   working-directory: actions/installer
+      #   run: make package
 
-      - name: Compare the expected and actual dist/ directories
-        working-directory: actions/installer
-        id: diff
+      # - name: Compare the expected and actual dist/ directories
+      #   working-directory: actions/installer
+      #   id: diff
+      #   run: |
+      #     set -euo pipefail
+      #     if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+      #       echo "Detected uncommitted changes after build.  See status below:"
+      #       git diff
+      #       exit 1
+      #     fi
+
+      # # If index.js was different from expected, upload the expected version as an artifact
+      # - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
+      #   if: ${{ failure() && steps.diff.conclusion == 'failure' }}
+      #   with:
+      #     name: dist
+      #     path: dist/
+
+      - name: Check documentation is up-to-date
+        if: ${{ contains(github.event.pull_request.body, '#label:release') }}
         run: |
           set -euo pipefail
-          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
-            echo "Detected uncommitted changes after build.  See status below:"
-            git diff
-            exit 1
-          fi
-
-      # If index.js was different from expected, upload the expected version as an artifact
-      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
-        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
-        with:
-          name: dist
-          path: dist/
+          echo "Hello World!"
+          ls
+          ./.github/workflows/scripts/pre-release/references.sh
+          echo "Farewell, cruel world"
