ci: Ensure all version references are up-to-date prior to release (#447)
* Create references.sh

Signed-off-by: Pedro Kaj Kjellerup Nacht <pnacht@google.com>

* WIP: check docs in pre-submits

Signed-off-by: Pedro Kaj Kjellerup Nacht <pnacht@google.com>

* Clean up

Signed-off-by: Pedro Kaj Kjellerup Nacht <pnacht@google.com>

* Fix based on comments

Signed-off-by: Pedro Kaj Kjellerup Nacht <pnacht@google.com>

* Add instructions to RELEASE.md

Signed-off-by: Pedro Kaj Kjellerup Nacht <pnacht@google.com>

* Check references match version in PR body

Signed-off-by: Pedro Kaj Kjellerup Nacht <pnacht@google.com>

---------

Signed-off-by: Pedro Kaj Kjellerup Nacht <pnacht@google.com>
Co-authored-by: laurentsimon <64505099+laurentsimon@users.noreply.github.com>

diff --git a/.github/workflows/pre-submit.actions.yml b/.github/workflows/pre-submit.actions.yml
--- a/.github/workflows/pre-submit.actions.yml
+++ b/.github/workflows/pre-submit.actions.yml
@@ -39,3 +39,24 @@ jobs:
         with:
           name: dist
           path: dist/
+
+  check-docs:
+    runs-on: ubuntu-latest
+    if: ${{ contains(github.event.pull_request.body, '#label:release') }}
+    env:
+      BODY: ${{ github.event.pull_request.body }}
+    steps:
+      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
+
+      - name: Check documentation is up-to-date
+        run: |
+          RELEASE_TAG=$(
+            echo "$BODY" | \
+            grep -oE '^[[:blank:]]*#label:release[[:blank:]]+v?[0-9]+\.[0-9]+\.[0-9]+' | \
+            sed -E 's/.*([0-9]+\.[0-9]+\.[0-9])/\1/'
+          )
+          if [[ -z "$RELEASE_TAG" ]]; then
+              echo "Invalid release PR body. Must include `#label:release vX.Y.Z"
+              exit 1
+          fi
+          RELEASE_TAG="${RELEASE_TAG}" ./.github/workflows/scripts/pre-release/references.sh
